import type {
  NavItem,
  Job,
  Candidate,
  CandidateProfile,
  PipelineCandidate,
  User,
  StatCard,
  SelectOption,
  ApplicationStatusEntry,
  PersonResult,
} from '@/types';

// ─── Navigation ──────────────────────────────────────────────────────────────

export const NAV_ITEMS: NavItem[] = [
  {
    label: 'Dashboard',
    href: '/dashboard',
    icon: 'LayoutDashboard',
  },
  {
    label: 'Sourcing',
    href: '/sourcing',
    icon: 'Search',
    children: [
      { label: 'People Search', href: '/sourcing/people' },
      { label: 'AI Sourcing Agent', href: '/sourcing/ai-agent' },
      { label: 'Unified Search', href: '/sourcing/unified' },
    ],
  },
  {
    label: 'Candidates',
    href: '/candidates',
    icon: 'Users',
  },
  {
    label: 'Pipeline',
    href: '/pipeline',
    icon: 'Layers',
  },
  {
    label: 'Job Postings',
    href: '/job-postings',
    icon: 'Briefcase',
  },
  {
    label: 'Talent Insights',
    href: '/talent-insights',
    icon: 'BarChart2',
  },
  {
    label: 'Onboarding',
    href: '/onboarding',
    icon: 'ClipboardList',
  },
  {
    label: 'Performance',
    href: '/performance',
    icon: 'Star',
  },
  {
    label: 'Reports',
    href: '/reports',
    icon: 'FileText',
  },
];

export const SETTINGS_NAV_ITEM: NavItem = {
  label: 'Settings',
  href: '/settings',
  icon: 'Settings',
};

// ─── Mock User ────────────────────────────────────────────────────────────────

export const MOCK_USER: User = {
  id: '1',
  name: 'John Doe',
  email: 'john@teamtalent.com',
  avatarUrl: '',
  role: 'HR Manager',
};

// ─── Mock Jobs ────────────────────────────────────────────────────────────────

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    title: 'Frontend Developer',
    description: 'Create stunning user interfaces and compelling web experiences that delight our customers.',
    department: 'Engineering',
    location: 'Remote',
    type: 'full-time',
    status: 'open',
    postedAt: '2024-01-15',
    applicantCount: 24,
  },
  {
    id: '2',
    title: 'Backend Developer',
    description: 'Develop robust backend solutions and scalable API architecture powering our platform.',
    department: 'Engineering',
    location: 'New York, NY',
    type: 'full-time',
    status: 'open',
    postedAt: '2024-01-12',
    applicantCount: 18,
  },
  {
    id: '3',
    title: 'Product Manager',
    description: 'Lead product development and drive the strategic roadmap across multiple teams.',
    department: 'Product',
    location: 'San Francisco, CA',
    type: 'full-time',
    status: 'open',
    postedAt: '2024-01-10',
    applicantCount: 31,
  },
  {
    id: '4',
    title: 'Senior Product Engineer',
    description: 'Build and scale our core platform with a sharp focus on reliability and performance.',
    department: 'Engineering',
    location: 'Remote',
    type: 'full-time',
    status: 'open',
    postedAt: '2024-01-08',
    applicantCount: 42,
  },
  {
    id: '5',
    title: 'UX Designer',
    description: 'Shape the user experience across our entire product suite from research to delivery.',
    department: 'Design',
    location: 'Austin, TX',
    type: 'full-time',
    status: 'open',
    postedAt: '2024-01-05',
    applicantCount: 15,
  },
  {
    id: '6',
    title: 'Data Analyst',
    description: 'Turn complex datasets into actionable business intelligence that drives growth decisions.',
    department: 'Analytics',
    location: 'Remote',
    type: 'contract',
    status: 'open',
    postedAt: '2024-01-03',
    applicantCount: 9,
  },
];

// ─── Mock Candidates ──────────────────────────────────────────────────────────

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    role: 'Frontend Developer',
    avatarUrl: '',
    status: 'interview',
    appliedAt: '2024-01-16',
    jobId: '1',
  },
  {
    id: '2',
    name: 'Michael Lee',
    role: 'Backend Developer',
    avatarUrl: '',
    status: 'screening',
    appliedAt: '2024-01-14',
    jobId: '2',
  },
  {
    id: '3',
    name: 'Emily Davis',
    role: 'Product Manager',
    avatarUrl: '',
    status: 'offer',
    appliedAt: '2024-01-11',
    jobId: '3',
  },
  {
    id: '4',
    name: 'James Wilson',
    role: 'Frontend Developer',
    avatarUrl: '',
    status: 'new',
    appliedAt: '2024-01-17',
    jobId: '1',
  },
  {
    id: '5',
    name: 'Priya Patel',
    role: 'Senior Product Engineer',
    avatarUrl: '',
    status: 'interview',
    appliedAt: '2024-01-09',
    jobId: '4',
  },
  {
    id: '6',
    name: 'Carlos Rivera',
    role: 'Data Analyst',
    avatarUrl: '',
    status: 'hired',
    appliedAt: '2024-01-04',
    jobId: '6',
  },
];

// ─── Candidates Page Data ─────────────────────────────────────────────────────

export const CANDIDATES_PAGE_DATA: CandidateProfile[] = [
  {
    id: 'cp1',
    name: 'Emma Johnson',
    role: 'Software Engineer',
    email: 'emmaj@company.com',
    phone: '+1 (415) 555-0192',
    location: 'San Francisco, CA',
    status: 'new',
    appliedAt: '2024-01-15',
    jobTitle: 'Frontend Developer',
    skills: ['React', 'TypeScript', 'Node.js', 'AWS'],
    experience: '5 years',
    education: 'BS Computer Science, Stanford University',
    notes: 'Strong technical background with excellent communication skills. Previously worked at a Series B startup.',
  },
  {
    id: 'cp2',
    name: 'Michael Brown',
    role: 'Data Analyst',
    email: 'michaelb@company.com',
    phone: '+1 (212) 555-0147',
    location: 'New York, NY',
    status: 'interview',
    appliedAt: '2024-01-12',
    jobTitle: 'Data Analyst',
    skills: ['Python', 'SQL', 'Tableau', 'Machine Learning'],
    experience: '3 years',
    education: 'MS Data Science, Columbia University',
  },
  {
    id: 'cp3',
    name: 'Sophia Martinez',
    role: 'Project Manager',
    email: 'sophiam@company.com',
    phone: '+1 (310) 555-0238',
    location: 'Los Angeles, CA',
    status: 'hired',
    appliedAt: '2024-01-08',
    jobTitle: 'Product Manager',
    skills: ['Agile', 'Jira', 'Product Strategy', 'Stakeholder Management'],
    experience: '7 years',
    education: 'MBA, UCLA Anderson',
    notes: 'Exceptional candidate. Strong PM background with proven track record in scaling teams.',
  },
  {
    id: 'cp4',
    name: 'James Wilson',
    role: 'Frontend Developer',
    email: 'jamesw@company.com',
    phone: '+1 (512) 555-0183',
    location: 'Austin, TX',
    status: 'screening',
    appliedAt: '2024-01-17',
    jobTitle: 'Frontend Developer',
    skills: ['Vue.js', 'JavaScript', 'CSS', 'Figma'],
    experience: '2 years',
  },
  {
    id: 'cp5',
    name: 'Priya Patel',
    role: 'Senior Product Engineer',
    email: 'priyap@company.com',
    phone: '+1 (650) 555-0261',
    location: 'Palo Alto, CA',
    status: 'interview',
    appliedAt: '2024-01-09',
    jobTitle: 'Senior Product Engineer',
    skills: ['Next.js', 'AWS', 'Docker', 'Kubernetes'],
    experience: '6 years',
    education: 'BS Software Engineering, UC Berkeley',
  },
  {
    id: 'cp6',
    name: 'Carlos Rivera',
    role: 'Data Analyst',
    email: 'carlosr@company.com',
    phone: '+1 (305) 555-0174',
    location: 'Miami, FL',
    status: 'hired',
    appliedAt: '2024-01-04',
    jobTitle: 'Data Analyst',
    skills: ['Python', 'R', 'Power BI', 'SQL'],
    experience: '4 years',
  },
  {
    id: 'cp7',
    name: 'Aisha Thompson',
    role: 'UX Designer',
    email: 'aishat@company.com',
    phone: '+1 (415) 555-0219',
    location: 'San Francisco, CA',
    status: 'offer',
    appliedAt: '2024-01-11',
    jobTitle: 'UX Designer',
    skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems'],
    experience: '4 years',
    education: 'BFA Interaction Design, RISD',
    notes: 'Portfolio is exceptional. Strong systems thinking and clear design rationale throughout.',
  },
  {
    id: 'cp8',
    name: 'Marcus Chen',
    role: 'Backend Developer',
    email: 'marcusc@company.com',
    phone: '+1 (206) 555-0142',
    location: 'Seattle, WA',
    status: 'screening',
    appliedAt: '2024-01-13',
    jobTitle: 'Backend Developer',
    skills: ['Python', 'Go', 'PostgreSQL', 'Redis'],
    experience: '3 years',
  },
  {
    id: 'cp9',
    name: 'Nina Rodriguez',
    role: 'Product Manager',
    email: 'ninar@company.com',
    phone: '+1 (737) 555-0198',
    location: 'Austin, TX',
    status: 'rejected',
    appliedAt: '2024-01-06',
    jobTitle: 'Product Manager',
    skills: ['Product Strategy', 'OKRs', 'Data Analysis', 'User Research'],
    experience: '5 years',
    education: 'MBA, UT Austin McCombs',
  },
];

// ─── Mock Pipeline Candidates ─────────────────────────────────────────────────

export const MOCK_PIPELINE_CANDIDATES: PipelineCandidate[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    role: 'Senior Product Engineer',
    avatarUrl: '',
    stage: 'interview',
    score: 88,
    tags: ['React', 'TypeScript', 'Node.js'],
    appliedAt: '2024-01-09',
    jobId: '4',
  },
  {
    id: '2',
    name: 'Marcus Chen',
    role: 'Senior Product Engineer',
    avatarUrl: '',
    stage: 'screening',
    score: 74,
    tags: ['Python', 'Go', 'PostgreSQL'],
    appliedAt: '2024-01-10',
    jobId: '4',
  },
  {
    id: '3',
    name: 'Aisha Thompson',
    role: 'Senior Product Engineer',
    avatarUrl: '',
    stage: 'technical',
    score: 92,
    tags: ['Rust', 'Systems', 'Distributed'],
    appliedAt: '2024-01-08',
    jobId: '4',
  },
  {
    id: '4',
    name: 'David Park',
    role: 'Senior Product Engineer',
    avatarUrl: '',
    stage: 'applied',
    score: 61,
    tags: ['Java', 'Spring', 'AWS'],
    appliedAt: '2024-01-11',
    jobId: '4',
  },
  {
    id: '5',
    name: 'Nina Rodriguez',
    role: 'Senior Product Engineer',
    avatarUrl: '',
    stage: 'offer',
    score: 95,
    tags: ['TypeScript', 'React', 'GraphQL'],
    appliedAt: '2024-01-07',
    jobId: '4',
  },
  {
    id: '6',
    name: 'Omar Hassan',
    role: 'Senior Product Engineer',
    avatarUrl: '',
    stage: 'screening',
    score: 69,
    tags: ['Vue.js', 'Laravel', 'MySQL'],
    appliedAt: '2024-01-12',
    jobId: '4',
  },
  {
    id: '7',
    name: 'Priya Patel',
    role: 'Senior Product Engineer',
    avatarUrl: '',
    stage: 'interview',
    score: 81,
    tags: ['Next.js', 'AWS', 'Docker'],
    appliedAt: '2024-01-06',
    jobId: '4',
  },
  {
    id: '8',
    name: 'Lena Fischer',
    role: 'Frontend Developer',
    avatarUrl: '',
    stage: 'applied',
    score: 58,
    tags: ['HTML', 'CSS', 'JavaScript'],
    appliedAt: '2024-01-13',
    jobId: '1',
  },
];

// ─── Pipeline Job Options ─────────────────────────────────────────────────────

export const PIPELINE_JOB_OPTIONS: SelectOption[] = MOCK_JOBS.map((job) => ({
  value: job.id,
  label: job.title,
}));

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

export const DASHBOARD_STATS: StatCard[] = [
  { label: 'Open Positions', value: '24', change: '+3 this week', positive: true },
  { label: 'Active Candidates', value: '142', change: '+18 this month', positive: true },
  { label: 'Interviews Scheduled', value: '9', change: '+2 today', positive: true },
  { label: 'Offers Sent', value: '3', change: '−1 from last week', positive: false },
];

// ─── Login Feature List ───────────────────────────────────────────────────────

export const LOGIN_FEATURES: string[] = [
  'AI-powered candidate sourcing',
  'Automated pipeline management',
  'Real-time talent insights',
  'Collaborative hiring workflows',
];

// ─── Job Postings — Applications Status ──────────────────────────────────────

export const MOCK_APPLICATION_STATUSES: ApplicationStatusEntry[] = [
  {
    id: '1',
    jobTitle: 'Software Engineer',
    appliedAgo: 'Applied 2 days ago',
    candidateName: 'Alex Martinez',
    candidateId: 'alex-martinez',
  },
  {
    id: '2',
    jobTitle: 'Product Designer',
    appliedAgo: 'Applied 5 days ago',
    candidateName: 'Sofia Patel',
    candidateId: 'sofia-patel',
  },
  {
    id: '3',
    jobTitle: 'Data Analyst',
    appliedAgo: 'Applied 1 week ago',
    candidateName: "Michael O'Connor",
    candidateId: 'michael-oconnor',
  },
  {
    id: '4',
    jobTitle: 'QA Engineer',
    appliedAgo: 'Applied 3 weeks ago',
    candidateName: 'Lina Rodriguez',
    candidateId: 'lina-rodriguez',
  },
];

// ─── People Search ────────────────────────────────────────────────────────────

export const MOCK_PEOPLE_SEARCH_RESULTS: PersonResult[] = [
  {
    id: 'psr1',
    name: 'Dr. Emily Zhang',
    title: 'Senior Scientist',
    company: 'BioTech Innovations',
    location: 'Sydney, Australia',
    yearsExp: 10,
    matchScore: 95,
    skills: ['Research Leadership', 'Molecular Biology', 'Clinical Trials', 'Python'],
    industry: 'Biotech',
    avatarUrl: '',
    locked: false,
  },
  {
    id: 'psr2',
    name: 'Dr. Sarah Lee',
    title: 'Research Director',
    company: 'Genomics Corp',
    location: 'Melbourne, Australia',
    yearsExp: 12,
    matchScore: 89,
    skills: ['Genomics', 'Bioinformatics', 'Team Leadership', 'Grant Writing'],
    industry: 'Biotech',
    avatarUrl: '',
    locked: false,
  },
  {
    id: 'psr3',
    name: 'Dr. Michael Tan',
    title: 'Biotech Consultant',
    company: 'PharmaTech',
    location: 'Perth, Australia',
    yearsExp: 9,
    matchScore: 87,
    skills: ['Drug Development', 'Regulatory Affairs', 'Clinical Research', 'Chemistry'],
    industry: 'Pharma',
    avatarUrl: '',
    locked: false,
  },
  {
    id: 'psr4',
    name: 'Dr. Priya Sharma',
    title: 'Principal Scientist',
    company: 'LifeSciences Ltd',
    location: 'Brisbane, Australia',
    yearsExp: 11,
    matchScore: 82,
    skills: ['Cell Biology', 'CRISPR', 'PCR', 'Flow Cytometry'],
    industry: 'Biotech',
    avatarUrl: '',
    locked: true,
  },
  {
    id: 'psr5',
    name: 'Dr. James Park',
    title: 'Head of Research',
    company: 'NovaBio',
    location: 'Sydney, Australia',
    yearsExp: 15,
    matchScore: 79,
    skills: ['Protein Engineering', 'Antibody Development', 'Leadership'],
    industry: 'Biotech',
    avatarUrl: '',
    locked: true,
    savedToShortlist: true,
  },
  {
    id: 'psr6',
    name: 'Dr. Aisha Hassan',
    title: 'Senior Research Scientist',
    company: 'MedGen Australia',
    location: 'Melbourne, Australia',
    yearsExp: 8,
    matchScore: 76,
    skills: ['Immunology', 'Vaccine Development', 'GMP', 'Regulatory'],
    industry: 'MedTech',
    avatarUrl: '',
    locked: true,
  },
];
