services:
  - type: web
    name: teamtalent-backend
    runtime: node
    rootDir: backend
    buildCommand: NODE_ENV=development npm install && npx prisma generate
    startCommand: npx tsx server.ts
    envVars:
      - key: NODE_ENV
        value: production
