import { Router } from 'express';
import authRoutes from './auth.routes';
import dashboardRoutes from './dashboard.routes';
import jobsRoutes from './jobs.routes';
import candidatesRoutes from './candidates.routes';
import applicationsRoutes from './applications.routes';
import onboardingRoutes from './onboarding.routes';
import performanceRoutes from './performance.routes';
import insightsRoutes from './insights.routes';
import reportsRoutes from './reports.routes';
import settingsRoutes from './settings.routes';
import teamRoutes from './team.routes';
import interviewsRoutes from './interviews.routes';
import offersRoutes from './offers.routes';
import employeesRoutes from './employees.routes';
import notificationsRoutes from './notifications.routes';
import workflowsRoutes from './workflows.routes';
import scorecardsRoutes from './scorecards.routes';
import evaluationsRoutes from './evaluations.routes';
import followUpsRoutes from './followups.routes';
import emailTemplatesRoutes from './email-templates.routes';
import projectsRoutes from './projects.routes';
import sequencesRoutes from './sequences.routes';
import feedbackFormsRoutes from './feedback-forms.routes';
import referralsRoutes from './referrals.routes';
import usersRoutes from './users.routes';
import gdprRoutes from './gdpr.routes';
import feedRoutes from './feed.routes';

const router = Router();

router.use('/auth',          authRoutes);
router.use('/dashboard',     dashboardRoutes);
router.use('/jobs',          jobsRoutes);
router.use('/candidates',    candidatesRoutes);
router.use('/applications',  applicationsRoutes);
router.use('/onboarding',    onboardingRoutes);
router.use('/performance',   performanceRoutes);
router.use('/insights',      insightsRoutes);
router.use('/reports',       reportsRoutes);
router.use('/settings',      settingsRoutes);
router.use('/team',          teamRoutes);
router.use('/interviews',    interviewsRoutes);
router.use('/offers',        offersRoutes);
router.use('/employees',     employeesRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/workflows',    workflowsRoutes);
router.use('/scorecards',   scorecardsRoutes);
router.use('/evaluations',  evaluationsRoutes);
router.use('/follow-ups',       followUpsRoutes);
router.use('/email-templates',  emailTemplatesRoutes);
router.use('/projects',         projectsRoutes);
router.use('/sequences',        sequencesRoutes);
router.use('/feedback-forms',   feedbackFormsRoutes);
router.use('/referrals',        referralsRoutes);
router.use('/users',            usersRoutes);
router.use('/gdpr',             gdprRoutes);
router.use('/feed',             feedRoutes);

export default router;
